# --- !Ups

create table "stories" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "phase" varchar not null
);

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

# --- !Downs

drop table "people" if exists;
drop table "stories" if exists;
